# https://learn.microsoft.com/en-us/azure/app-service/tutorial-custom-container?tabs=azure-cli&pivots=container-linux
# https://learn.microsoft.com/en-us/azure/app-service/deploy-container-github-action?tabs=publish-profile
#
name: EvaDB-REST-CONTAINER

on:
  push:
    branches:
      - prod
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/docker-login@v1
        with:
                login-server: evadbrestdocker.azurecr.io
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t evadbrestdocker.azurecr.io/evadb-rest-image:${{ github.sha }}
          docker push evadbrestdocker.azurecr.io/evadb-rest-image:${{ github.sha }}  


     
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'evadb-rest-docker-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5F7A87306CA94655BB8A4671B1ACC7C4 }}
          images: 'evadbrestdocker.azurecr.io/evadb-rest-image:${{ github.sha }}'
